In [135]:
import numpy as np
from collections import Counter
np.random.seed(1)

In [175]:
# [hr, steals, age]
# in our constructed example, over 20 HR or 20 steals is an all-star
# age is an irrelevant dimension
balanced_all_star = np.array([40, 20, 21])
average = np.array([20, 5, 28])
hr_all_star = np.array([50, 1, 28])
bench = np.array([1, 7, 22])
almost = np.array([19, 19, 23])
steals_all_star = np.array([0, 100, 26])

players = np.array([balanced_all_star, average, hr_all_star, bench, almost, steals_all_star]) / 100.
actual_labels = np.array([1, 0, 1, 0, 0, 1])


# generate lots of players based on rules
more_players = []
more_labels = []
def classify(p):
    hr, steals, age = p
    if hr > 20 or steals > 20:
        return 1
    return 0

for i in range(10000):
    player = np.random.randint(40, size=(3,))
    more_players.append(player)
    more_labels.append(classify(player))
    
print('Generated {} players ({})'.format(len(more_players), Counter(more_labels)))

normalized_players = np.array([p / 40. for p in more_players])
print(normalized_players[0])
print(more_labels[0])
print(normalized_players[0] * 40)

print(normalized_players[3])
print(more_labels[3])
print(normalized_players[3] * 40)

Generated 10000 players (Counter({1: 7290, 0: 2710}))
[ 0.575  0.35   0.625]
1
[ 23.  14.  25.]
[ 0.125  0.775  0.8  ]
1
[  5.  31.  32.]


In [261]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
    
def deriv_sigmoid(x):
    return x * (1 - x)

class NN(object):
    def __init__(self, training, labels):
        self.training = training
        self.labels = labels
        self.weights = np.random.rand(3)
        
    def predict(self, input):
        return sigmoid(np.dot(input, self.weights))
    
    def train(self, iterations):
        error = None
        for i in range(iterations):
            output_labels = self.predict(self.training)
            error = self.labels - output_labels
            # gradient descent
            nudge = np.dot(self.training.T, error * deriv_sigmoid(output_labels))
            self.weights += nudge
        
        print('Error', error)
    
    def print_accuracy(self):
        output_labels = self.predict(self.training)
        correct = 0
        for i, l in enumerate(output_labels):
            if l == self.labels[i]:
                correct += 1
        
        return round(correct / float(len(self.labels)), 2)
            
        

In [266]:
nn = NN(normalized_players, )
print(nn.weights)
# we know age should be 0 and steals and HR should have some positive weight

[ 0.97596911  0.84524188  0.83268899]
