In [1]:
import numpy as np

In [12]:
training_set_inputs = np.array([
    [0, 0, 1], # labeled 0
    [1, 1, 1], # labeled 1
    [1, 0, 1], # labeled 1
    [0, 1, 1]],# labeled 0
)

# below is same as np.array([0, 1, 1, 0]).T
training_set_outputs = np.array([
    [0], 
    [1], 
    [1], 
    [0]]
)

for i, t in enumerate(training_set_inputs):
    if t[0] == 0:
        assert(training_set_outputs[i][0] == 0)
    else:
        assert(training_set_outputs[i][0] == 1)

In [44]:
np.random.seed(1)
weights = 2 * np.random.random((3, 1)) - 1
print(weights)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [45]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
    
def deriv_sigmoid(x):
    # A little misleading - derivative is actually
    # sigmoid(x) * (1 - sigmoid(x))
    # but x here is preprocessed as sigmoid x
    # See http://kawahara.ca/how-to-compute-the-derivative-of-a-sigmoid-function-fully-worked-example/
    return x * (1 - x)

for iteration in range(1):
    # make a random prediction
    print(training_set_inputs.shape)
    print(weights)
    first_layer = np.dot(training_set_inputs, weights)
    print(first_layer)
    print(first_layer.shape)

    # non linearity applied - convert numbers to probabilities - scale the random predictions
    # forward prop
    predictions = sigmoid(first_layer)
    
    # get the error
    error = training_set_outputs - predictions
    
    # Scale the low confidence predictions (close to 0 predictions) bby the error
    # Conversely, do nothing to the high confidence predictions
    # if close to 0.5, deriv_sigmoid maxes out
    deriv = deriv_sigmoid(predictions)
    error_weighted_derivative = error * deriv
    weight_update = np.dot(training_set_inputs.T, error_weighted_derivative)
    weights += weight_update

print('Ending weights', weights)
[[-0.99977125], [-0.72507825], [-1.16572724], [-0.55912226]]

(4, 3)
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
[[-0.99977125]
 [-0.72507825]
 [-1.16572724]
 [-0.55912226]]
(4, 1)
Ending weights [[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]


In [30]:
def predict(weights, test):
    w1, w2, w3 = np.ndarray.flatten(weights)
    s1, s2, s3 = test
    return w1 * s2 + w2 * s2 + w3 * s3

predict(weights, [1, 1, 0])

0.2746929962894642